name: deploy-prod
on:
  workflow_dispatch:
    inputs: 
      Tag:
        type: string
        description: 'Tag'    
        required: true
      prod:
        type: boolean
        description: 'deploy prod'    
        required: false
        default: 'false'          
      prod-east:
        type: boolean
        description: 'deploy prod east'    
        required: false
        default: 'false'
        
jobs:
  prod-deploy:
    if: success() && github.event.inputs.prod == 'true'
    uses: albertsons/esgh-central-workflow-aks/.github/workflows/oneclick-deploy-prod.yml@master
    with:
      ACTIONSFILE: "Actionsfile/prod"
      TAG: ${{ github.event.inputs.Tag }}     
    secrets:
      REGISTRY_USER: ${{ secrets.ACR_USER }}
      REGISTRY_PWD: ${{ secrets.ACR_PWD }} 
      KUBECONFIG: ${{ secrets.ESCO_AKSPCI_PROD_WESTUS_CLUSTER_01 }} 
  Deploy-Status-check-workflow:
    needs: prod-deploy
    if: success()
    uses: albertsons/esgh-central-workflow-aks/.github/workflows/Deploy-Status-check.yml@master
    with:
      ACTIONSFILE: "Actionsfile/prod" 
    secrets:      
      KUBECONFIG: ${{ secrets.ESCO_AKSPCI_PROD_WESTUS_CLUSTER_01 }}
  prod-east-deploy:
    if: success() && github.event.inputs.prod-east == 'true'
    uses: albertsons/esgh-central-workflow-aks/.github/workflows/oneclick-deploy-prod.yml@master
    with:
      ACTIONSFILE: "Actionsfile/prod-east"
      TAG: ${{ github.event.inputs.Tag }}
    secrets:
      REGISTRY_USER: ${{ secrets.ACR_USER }}
      REGISTRY_PWD: ${{ secrets.ACR_PWD }} 
      KUBECONFIG: ${{ secrets.ESCO_AKSPCI_PROD_EASTUS_CLUSTER_01 }}
  Deploy-Status-check-prod-east:
    needs: prod-east-deploy
    if: success()
    uses: albertsons/esgh-central-workflow-aks/.github/workflows/Deploy-Status-check.yml@master
    with:
      ACTIONSFILE: "Actionsfile/prod-east" 
    secrets:      
      KUBECONFIG: ${{ secrets.ESCO_AKSPCI_PROD_EASTUS_CLUSTER_01 }}
