name: deploy-nonprod
on:
  workflow_dispatch:
    inputs: 
      dev:
        type: boolean
        description: 'deploy dev'    
        required: false
        default: 'false'          
      qa1:
        type: boolean
        description: 'deploy qa1'    
        required: false
        default: 'false'   
      Tag:
        type: string
        description: 'Tag'    
        required: true  
jobs:
  dev-deploy:
    if: github.event.inputs.dev == 'true'
    uses: albertsons/esgh-central-workflow-aks/.github/workflows/oneclick-deploy-nonprod.yml@master
    with:
      ACTIONSFILE: "Actionsfile/dev"
      TAG: ${{ github.event.inputs.Tag }}     
    secrets:
      REGISTRY_USER: ${{ secrets.ACR_USER }}
      REGISTRY_PWD: ${{ secrets.ACR_PWD }} 
      KUBECONFIG: ${{ secrets.ESCO_AKSPHI_NONPROD_WESTUS_CLUSTER_01 }} 
  Deploy-Status-check-dev:
    needs: dev-deploy
    if: success()
    uses: albertsons/esgh-central-workflow-aks/.github/workflows/Deploy-Status-check.yml@master
    with:
      ACTIONSFILE: "Actionsfile/qa1" 
    secrets:  
      KUBECONFIG: ${{ secrets.ESCO_AKSPHI_NONPROD_WESTUS_CLUSTER_01 }}   
  qa1-deploy:
    if: github.event.inputs.qa1 == 'true'
    uses: albertsons/esgh-central-workflow-aks/.github/workflows/oneclick-deploy-nonprod.yml@master
    with:
      ACTIONSFILE: "Actionsfile/qa1"
      TAG: ${{ github.event.inputs.Tag }}
    secrets:
      REGISTRY_USER: ${{ secrets.ACR_USER }}
      REGISTRY_PWD: ${{ secrets.ACR_PWD }} 
      KUBECONFIG: ${{ secrets.ESCO_AKSPHI_NONPROD_WESTUS_CLUSTER_01 }} 
  Deploy-Status-check-qa1:
    needs: qa1-deploy
    if: success()
    uses: albertsons/esgh-central-workflow-aks/.github/workflows/Deploy-Status-check.yml@master
    with:
      ACTIONSFILE: "Actionsfile/qa1" 
    secrets:  
      KUBECONFIG: ${{ secrets.ESCO_AKSPHI_NONPROD_WESTUS_CLUSTER_01 }}
