name: oneclick-ci-maven-nonprod

on:
 workflow_call:
   inputs:
      ACTIONSFILE:    
        required: true
        type: string
      TAG:    
        required: true
        type: string 
      build_type:
        required: true
        type: string
      javaVersion:
        required: true
        type: number
      branch_name: 
         required: true
         type: string

       

env: 
  ACTIONSFILE: ${{ inputs.ACTIONSFILE }}
  TAG: ${{ inputs.TAG }}
jobs:
  Maven_Build:
    runs-on: [ aks ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          overwrite-settings: false
          distribution: 'adopt'
          #cache: maven
      - name: Build with Maven 
        run: |
          if [[ ${{ inputs.build_type }} == 'maven' ]]
          then
          cp /home/es00gh/.m2/settings.xml .
          #chmod +x mvnw
          ls -l 
          mvn clean install --settings settings.xml
          fi
      - name: Build with Maven Wrapper
        run: |
          if [[ ${{ inputs.build_type }} == 'mavenwrapper' ]]
          then
          cp /home/es00gh/.m2/settings.xml .
          chmod +x mvnw
          ls -l 
          ./mvnw clean install --settings settings.xml
          fi
      - uses: actions/upload-artifact@v2
        with:
          name: AppArtifacts
          path: |
            ./target/*.jar 
            settings.xml
      - name: clean workspace
        uses: albertsons/esgh-workspace-clean@v2-bash
      - name: Printing workspace cleaned message
        run: |
          echo "Workspace cleared for run ID ${{ github.run_number }}"      
