name: PR Scan
on:
 workflow_call:
  inputs:
    javaVersion:
      required: true
      type: number
  secrets:
     SONAR_TOKEN:
       required: true
     SONAR_HOST_URL:
       required: true
     SONAR_CONTINUEONERROR_NONPROD:
       required: false
     PERSONAL_ACCESS_TOKEN:
       required: true
jobs:
  scanning:
     name: PR Scanning
     runs-on: [ AKS ]
     continue-on-error: ${{ secrets.SONAR_CONTINUEONERROR_NONPROD == 'true' }}
     steps:
      - uses: actions/checkout@v2
      - name: Set up JDK '${{ inputs.javaVersion }}'
        uses: actions/setup-java@v2
        with:
          java-version: '${{ inputs.javaVersion }}'
          overwrite-settings: false
          distribution: 'adopt'
      - name: Build
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}  
        run: |
          cp /home/es00gh/settings.xml .
          mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install org.jacoco:jacoco-maven-plugin:report  --settings settings.xml
      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          overwrite-settings: false
          distribution: 'adopt'  
      - name: Sonar analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}  
        run: |
          mvn sonar:sonar -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} -Dsonar.login=${{ secrets.SONAR_TOKEN }}  --settings settings.xml

      - name: clean workspace
        uses: albertsons/esgh-workspace-clean@v2-bash
      - name: Printing workspace cleaned message
        run: |
          echo "Workspace cleared for run ID ${{ github.run_number }}"   
