name: PR Scan node
on:
 workflow_call:
  inputs:
    NodeVersion:
        type: string    
        default: 14
    command:
        type: string
        required: false
  secrets:
     SONAR_TOKEN:
       required: true
     SONAR_HOST_URL:
       required: true
     PERSONAL_ACCESS_TOKEN:
       required: true
     SONAR_CONTINUEONERROR_NONPROD:
       required: false
jobs:
  scanning:
     name: PR Scanning
     runs-on: [ AKS ]
     steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          overwrite-settings: false
          distribution: 'adopt'
      - name: Set up node 
        uses: actions/setup-node@v3
        with:
          node-version: '${{ inputs.NodeVersion }}'
      - name: Build and analyze
        continue-on-error: ${{ secrets.SONAR_CONTINUEONERROR_NONPROD == 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          export PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          export GIT_COMMIT=`git rev-parse --short HEAD`
          echo ${PR_NUMBER}
          echo ${GIT_COMMIT}
          npm install
          ${{ inputs.command }}
          npm run sonar -Dsonar.host.url=https://sonarqube.albertsons.com  -Dsonar.login=${{ secrets.SONAR_TOKEN }}
          #npm run sonar -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} -Dsonar.login=${{ secrets.SONAR_TOKEN }}          
