name: rest_assured_test_central

on:
 workflow_call:
   inputs:
      RESTASSURED_REPO:    
        required: true
        type: string
      TEST_ENV:
        required: true
        type: string
   secrets:
     PERSONAL_ACCESS_TOKEN:
       required: true 
env: 
  RESTASSURED_REPO: ${{ inputs.RESTASSURED_REPO }}
  TEST_ENV: ${{ inputs.TEST_ENV }}
jobs:
  test-case-rest-assured:
    runs-on: [ pilot ]
    steps:
      - uses: actions/checkout@v2
      - name: rest-assured-test
        uses: actions/checkout@v2    
        with:
          repository: ${{ env.RESTASSURED_REPO }}
          ref: master
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: ./.github/${{ env.RESTASSURED_REPO }}
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          overwrite-settings: false
          distribution: 'adopt'
          #cache: maven
      - name: Build with Maven Wrapper
        run: |
          cp /home/es00gh/.m2/settings.xml .
          chmod +x mvnw
          ls -l 
          ./mvnw clean install --settings settings.xml         
      - name: Run Testcase
        run: |
          cp settings.xml ./.github/${{ env.RESTASSURED_REPO }}
          cd ./.github/${{ env.RESTASSURED_REPO }}
          mvn clean site -Dsuite=debug.xml -Denv=${{ env.TEST_ENV }} -DtestEnv=${{ env.TEST_ENV }} --settings settings.xml
